wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1661403384.910031
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.2
      6: 4.18.0
      8:
      - 5
batch_size:
  desc: null
  value: 16
bert_pretrained_dir:
  desc: null
  value: bert-base-uncased
checkpoint_dir:
  desc: null
  value: /home/wansik/QA/quote_attribution/checkpoint
classifier_intermediate_dim:
  desc: null
  value: 100
dropout:
  desc: null
  value: 0.5
len_limit:
  desc: null
  value: 510
lr:
  desc: null
  value: 2.0e-05
lr_decay:
  desc: null
  value: 0.95
margin:
  desc: null
  value: 1.0
model_name:
  desc: null
  value: CSN
name_list:
  desc: null
  value: /home/wansik/QA/quote_attribution/data/pnp_name_list.txt
nonlinear_type:
  desc: null
  value: relu
num_epochs:
  desc: null
  value: 50
optimizer:
  desc: null
  value: adam
patience:
  desc: null
  value: 10
pooling_type:
  desc: null
  value: max_pooling
test_file:
  desc: null
  value: /home/wansik/QA/quote_attribution/data/test/pnp_test.txt
train_file:
  desc: null
  value: /home/wansik/QA/quote_attribution/data/train/pnp_train.txt
val_file:
  desc: null
  value: /home/wansik/QA/quote_attribution/data/val/pnp_val.txt
window_size:
  desc: null
  value: 10
